version: '3.6'
services:
    nginx:
        build: docker/nginx
        restart: always
        ports:
            - "${PORT-80}:80"
        volumes:
            - './:/usr/share/nginx/html'
    php-fpm:
        build: docker/php
        restart: always
        volumes:
            - './:/usr/share/nginx/html'
